
Database:
  DBType: mysql
  Username: root
  Password: Lyj7395828
  Host: 127.0.0.1:3306
  DBName: shopeepay_entrytask_db
  Charset: utf8mb4
  ParseTime: True
  MaxIdleConns: 100
  MaxOpenConns: 100

Redis:
  Host: 127.0.0.1:6379
  DBIndex: 0

RpcClient:
  RPCHost: 127.0.0.1:8001
  connNum: 20

HttpServer:
  Mode: debug
  Host: 127.0.0.1
  Port: 8000
  ReadTimeout: 60
  WriteTimeout: 60

RpcServer:
  Mode: debug
  Host: 127.0.0.1
  Port: 8001
  ReadTimeout: 60
  WriteTimeout: 60

